name: flutter_fire_bug_1
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
#  cloud_firestore:
#    git:
#      url: git@github.com:agent3bood/flutterfire.git
#      ref: fix/startAfterDocument_encode_values
#      path: packages/cloud_firestore/cloud_firestore

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
